# Generated by Django 5.2.10 on 2026-01-30 16:43

import django.db.models.deletion
import inventory.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True, validators=[inventory.models.validate_barcode], verbose_name='Barcode (94...)')),
                ('status', models.CharField(choices=[('STORED', 'Gelagert'), ('TRANSIT', 'Im Transit'), ('LENT', 'Verliehen'), ('LOST', 'Verloren/Unbekannt'), ('EXT', 'Extern')], default='STORED', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Inhalt / Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Box',
                'verbose_name_plural': 'Boxen',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('color', models.CharField(default='#203564', max_length=7, verbose_name='Farbe (Hex)')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_external', models.BooleanField(default=False, help_text='z.B. Nachbar, Verliehen', verbose_name='Ist extern/Transit')),
            ],
            options={
                'verbose_name': 'Lagerort',
                'verbose_name_plural': 'Lagerorte',
            },
        ),
        migrations.CreateModel(
            name='BoxImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='box_images/', verbose_name='Bild')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='categories',
            field=models.ManyToManyField(blank=True, to='inventory.category', verbose_name='Kategorien'),
        ),
        migrations.CreateModel(
            name='HistoricalBox',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=20, validators=[inventory.models.validate_barcode], verbose_name='Barcode (94...)')),
                ('status', models.CharField(choices=[('STORED', 'Gelagert'), ('TRANSIT', 'Im Transit'), ('LENT', 'Verliehen'), ('LOST', 'Verloren/Unbekannt'), ('EXT', 'Extern')], default='STORED', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Inhalt / Beschreibung')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.location', verbose_name='Lagerort')),
            ],
            options={
                'verbose_name': 'historical Box',
                'verbose_name_plural': 'historical Boxen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Lagerort'),
        ),
    ]
