# Generated by Django 5.2.10 on 2026-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('STORED', 'Gelagert'), ('ACCESS', 'Im Zugriff'), ('TRANSIT', 'Im Transit'), ('LENT', 'Verliehen'), ('LOST', 'Verloren/Unbekannt'), ('EXT', 'Extern')], default='STORED', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='status',
            field=models.CharField(choices=[('STORED', 'Gelagert'), ('ACCESS', 'Im Zugriff'), ('TRANSIT', 'Im Transit'), ('LENT', 'Verliehen'), ('LOST', 'Verloren/Unbekannt'), ('EXT', 'Extern')], default='STORED', max_length=10, verbose_name='Status'),
        ),
    ]
