# Generated by Django 5.2.11 on 2026-02-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_box_status_alter_historicalbox_status'),
    ]

    operations = [
    ]
