# Generated by Django 5.2.11 on 2026-02-12 18:27

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_setup_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBox_categories',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('box', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.box')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.category')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.historicalbox')),
            ],
            options={
                'verbose_name': 'HistoricalBox_categories',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
